# Generated by Django 6.0.4 on 2026-04-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadResponsable',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de ERP',
                'verbose_name_plural': 'Tipos de ERP',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_radicacion_inicial', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('copago', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('erp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.entidadresponsable')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RAD', 'Radicación Real'), ('DEV', 'Devolución'), ('GLO_INI', 'Glosa Inicial (Informativa)'), ('GLO_ACEP', 'Glosa Aceptada IPS (Afecta Saldo)'), ('GLO_LEV', 'Glosa Levantada ERP'), ('ABONO', 'Abono/Pago (Afecta Saldo)'), ('RTF', 'Retención en la Fuente (Afecta Saldo)')], max_length=10)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='facturacion.factura')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='entidadresponsable',
            name='tipo_erp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='facturacion.tipoerp'),
        ),
    ]
