# Generated by Django 6.0.4 on 2026-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_glosa_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
