# Generated by Django 6.0.4 on 2026-05-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_factura_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioDimension',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
                ('nombre_dia', models.CharField(max_length=20)),
                ('trimestre', models.CharField(max_length=10)),
                ('semana', models.IntegerField()),
                ('es_fin_semana', models.BooleanField(default=False)),
                ('es_festivo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['ano', 'mes'], name='facturacion_ano_d966ca_idx'), models.Index(fields=['ano'], name='facturacion_ano_f0ff1f_idx'), models.Index(fields=['trimestre'], name='facturacion_trimest_7765cd_idx')],
            },
        ),
    ]
