# Generated by Django 6.0.4 on 2026-06-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_calendariodimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_importacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
