# Generated by Django 6.0.6 on 2026-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_factura_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pae_cambios',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
