# Generated by Django 6.0.5 on 2026-06-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_factura_pae_cambios'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='datos_origen',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
