# Generated by Django 6.0.5 on 2026-06-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_factura_datos_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pae_datos_origen',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
