# Generated by Django 6.0.7 on 2026-08-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_factura_pae_datos_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('DIF', 'DIF'), ('PAE', 'PAE')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict, null=True)),
                ('detalles', models.JSONField(blank=True, default=list, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
