# Generated by Django 6.0.5 on 2026-08-20 02:35

import django.db.models.deletion
from django.db import migrations, models


def crear_environment_inicial(apps, schema_editor):
    Environment = apps.get_model('facturacion', 'Environment')
    for numero in range(1, 11):
        Environment.objects.get_or_create(numero=numero)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RunPython(crear_environment_inicial, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='factura',
            name='num_factura',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='entidadresponsable',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AddField(
            model_name='eventocartera',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AddField(
            model_name='factura',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AddField(
            model_name='tipoerp',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AddConstraint(
            model_name='entidadresponsable',
            constraint=models.UniqueConstraint(fields=('environment', 'nit'), name='entidad_environment_nit'),
        ),
        migrations.AddConstraint(
            model_name='tipoerp',
            constraint=models.UniqueConstraint(fields=('environment', 'nombre'), name='tipoerp_environment_nombre'),
        ),
    ]
