# Generated by Django 6.0.5 on 2026-08-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_environment_entidadresponsable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoerp',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
