# Generated by Django 6.0.5 on 2026-08-20 02:43

import django.db.models.deletion
import facturacion.environment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_tipoerp_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadresponsable',
            name='environment',
            field=models.ForeignKey(default=facturacion.environment.get_current_environment_id, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AlterField(
            model_name='eventocartera',
            name='environment',
            field=models.ForeignKey(default=facturacion.environment.get_current_environment_id, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='environment',
            field=models.ForeignKey(default=facturacion.environment.get_current_environment_id, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='environment',
            field=models.ForeignKey(default=facturacion.environment.get_current_environment_id, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
        migrations.AlterField(
            model_name='tipoerp',
            name='environment',
            field=models.ForeignKey(default=facturacion.environment.get_current_environment_id, on_delete=django.db.models.deletion.CASCADE, to='facturacion.environment'),
        ),
    ]
